### ISSUE TITLE
Se solicito el nombre TiposTecnicos 

### ISSUE THREAD

**Issue by enelramon** [Angelluis800/RegistroTecnicos#13]
Se solicitó el nombre TiposTecnicos  para las clases, también recordar que las instancias van en singular.

**Comment by Angelluis800** [comment]
Efectivamente el proyecto debe llamarse de esta manera, pero debo de aclarar que trabajé en una nueva rama del proyecto RegistroTécnicos en donde coloqué este nombre "TipoTécnicos", puede verificarlo. Hice push y realicé un pull request, todos los cambios se guardaron en el master.

**Comment by Angelluis800** [comment]
Completado
