### ISSUE TITLE
Quitar delay

### ISSUE THREAD

**Issue by enelramon** [Angelluis800/RegistroTecnicos#5]
https://github.com/Angelluis800/RegistroTecnicos/blob/bf3c4c38b104296a9737b542cb9bf2189439cd7a/RegistroTecnicos/Components/Pages/TecnicosPages/Index.razor#L60

**Comment by Angelluis800** [comment]
El Project Manager Cristopher Marte notificó este issue anteriormente, ya ha sido solucionado
